config/routes.rb
Rails.application.routes.draw do
  resources :campuses
  resources :classrooms
  resources :course_types
  resources :courses
  resources :bookings
  devise_for :users
  resources :users, only: [:index, :show]
  root to: "courses#index" 
  
  

end

app/controllers/campuses_controller.rb
class CampusesController < ApplicationController
  before_action :set_campus, only: [:show, :edit, :update, :destroy]

  authorize_resource
  # GET /campuses
  # GET /campuses.json
  def index
    @campuses = Campus.all
  end

  # GET /campuses/1
  # GET /campuses/1.json
  def show
  end

  # GET /campuses/new
  def new
    @campus = Campus.new
  end

  # GET /campuses/1/edit
  def edit
  end

  # POST /campuses
  # POST /campuses.json
  def create
    @campus = Campus.new(campus_params)

    respond_to do |format|
      if @campus.save
        format.html { redirect_to @campus, notice: 'Campus was successfully created.' }
        format.json { render :show, status: :created, location: @campus }
      else
        format.html { render :new }
        format.json { render json: @campus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campuses/1
  # PATCH/PUT /campuses/1.json
  def update
    respond_to do |format|
      if @campus.update(campus_params)
        format.html { redirect_to @campus, notice: 'Campus was successfully updated.' }
        format.json { render :show, status: :ok, location: @campus }
      else
        format.html { render :edit }
        format.json { render json: @campus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campuses/1
  # DELETE /campuses/1.json
  def destroy
    @campus.destroy
    respond_to do |format|
      format.html { redirect_to campuses_url, notice: 'Campus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campus
      @campus = Campus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campus_params
      params.require(:campus).permit(:name, :address, :campus_location_image)
    end
end

app/helpers/campuses_helper.rb
module CampusesHelper
end

app/views/campuses/_form.html.erb
<%= form_for(@campus) do |f| %>
  <% if @campus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campus.errors.count, "error") %> prohibited this campus from being saved:</h2>

      <ul>
      <% @campus.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :campus_location_image %><br />
    <%= f.file_field :campus_location_image %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campuses/edit.html.erb
<body class="edit">
  <h1>Editing Campus</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @campus %> |
  <%= link_to 'Back', campuses_path %>
</body>

app/views/campuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>GA Campuses</h1>

<% if user_signed_in? %>  
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <!-- <th colspan="3"></th> -->
      </tr>
    </thead>

    <tbody>
      <% @campuses.each do |campus| %>
        <tr>
          <td><strong><%= campus.name %></strong></td>
          <td><%= campus.address %></td>
          <!-- <td><%= link_to 'Show', campus %></td> -->
          <td><%= image_tag campus.campus_location_image.url %></td>
          <td>
            <% if can? :update, campus %>
              <button class="change"><%= link_to 'Edit', edit_campus_path(campus) %></button>
            <% end %>
          </td>
          <td>
            <% if can? :destroy, campus %>
              <button class="change"><%= link_to 'Delete', campus, method: :delete, data: { confirm: 'Are you sure?' } %></button>
            <% end %>      
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <p> 
    <% if can? :create, Campus %>
    <button class="new"><%= link_to 'New Campus', new_campus_path %></button>
    <% end %>    
  </p>

<% else %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @campuses.each do |campus| %>
        <tr>
          <td><strong><%= campus.name %></strong></td>
          <td><%= campus.address %></td>
          <td><%= image_tag campus.campus_location_image.url %></td>
          <!-- <td><%= link_to 'Show', campus %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
  

app/views/campuses/new.html.erb
<body class="edit">
  <h1>New Campus</h1>

  <%= render 'form' %>

  <%= link_to 'Back', campuses_path %>
</body>

app/views/campuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @campus.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @campus.address %>
</p>

<%= link_to 'Edit', edit_campus_path(@campus) %> |
<%= link_to 'Back', campuses_path %>