config/routes.rb
Rails.application.routes.draw do
  resources :campuses
  resources :classrooms
  resources :course_types
  resources :courses
  resources :bookings
  devise_for :users
  resources :users, only: [:index, :show]
  root to: "courses#index" 
  
  

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  authorize_resource
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:course_type_id, :classroom_id, :name, :start_date, :end_date, :description, :capacity)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_type_id %><br>
    <%= f.collection_select :course_type_id, CourseType.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :classroom_id %><br>
    <%= f.collection_select :classroom_id, Classroom.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<body class="edit">
  <h1>Editing Course</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @course %> |
  <%= link_to 'Back', courses_path %>
</body>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Courses</h1> 

<% if user_signed_in? %>  
  <table>
    <thead>
      <tr>
        <th>Course type</th>
        <th>Classroom</th>
        <th>Name</th>
        <th>Start date</th>
        <th>End date</th>
        <th>Description</th>
        <th>Capacity</th>
        <!-- <th colspan="3"></th> -->
      </tr>
    </thead>

    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td><strong><%= course.name %></strong></td>
          <td><%= course.course_type.name %></td>
          <td><%= course.classroom.name %></td>
          <td><%= course.start_date %></td>
          <td><%= course.end_date %></td>
          <td><%= course.description %></td>
          <td><%= course.capacity %></td>
          <!-- <td><%= link_to 'Show', course %></td> -->
          <td>
            <% if can? :update, course %>
              <button class="change"><%= link_to 'Edit', edit_course_path(course) %></button></td>
            <% end %>
          <td>
            <% if can? :destroy, course %>
              <button class="change"><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></button>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <p>
    <% if can? :create, Course %> <!-- Course is a class -->
      <button class="new"><%= link_to 'New Course', new_course_path %></button>
    <% end %>
  </p>


<% else %>
  <table>
    <thead>
      <tr>
        <th>Course type</th>
        <th>Classroom</th>
        <th>Name</th>
        <th>Start date</th>
        <th>End date</th>
        <th>Description</th>
        <th>Capacity</th>
        <!-- <th colspan="3"></th> -->
      </tr>
    </thead>

    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td><%= course.course_type.name %></td>
          <td><%= course.classroom.name %></td>
          <td><%= course.name %></td>
          <td><%= course.start_date %></td>
          <td><%= course.end_date %></td>
          <td><%= course.description %></td>
          <td><%= course.capacity %></td>
          <!-- <td><%= link_to 'Show', course %></td> -->
          <!-- <td><%= link_to 'Edit', edit_course_path(course) %></td> -->
          <!-- <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/courses/new.html.erb
<body class="edit">
  <h1>New Course</h1>

  <%= render 'form' %>

  <%= link_to 'Back', courses_path %>
</body>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course type:</strong>
  <%= @course.course_type_id %>
</p>

<p>
  <strong>Classroom:</strong>
  <%= @course.classroom_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @course.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @course.end_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @course.capacity %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>