config/routes.rb
Rails.application.routes.draw do
  resources :campuses
  resources :classrooms
  resources :course_types
  resources :courses
  resources :bookings
  devise_for :users
  resources :users, only: [:index, :show]
  root to: "courses#index" 
  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to 'GA Scheduler', courses_path %></h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <% if user_signed_in? %> 
        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <li><%= link_to current_user.email, user_path(current_user)%></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>    
          </ul>

          <!-- Left Nav Section -->
          <ul class="left">
            <li class="has-dropdown">
              <%= link_to 'Bookings', "#" %>
              <ul class="dropdown">
                <li><%= link_to 'View', bookings_path %></li>
                <li><%= link_to 'New', new_booking_path %></li>
              </ul>
            </li>
            <li class="has-dropdown">
              <%= link_to 'Courses', "#" %>
              <ul class="dropdown">
                <li><%= link_to 'All', courses_path %></li>
                <li><%= link_to 'Types', course_types_path %></li>
                <li><%= link_to 'Classrooms', classrooms_path %></li>
                <li><%= link_to 'Create', new_course_path %></li>
              </ul>
            </li>
            <li><%= link_to 'Members', users_path %></li>
            <li><%= link_to 'Campuses', campuses_path %></li>
          </ul>
        </section>

      <% else %>
        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <li><%= link_to "Login", new_user_session_path %></li>
            <li><%= link_to "Create an account", new_user_registration_path %></li>
          </ul>

          <!-- Left Nav Section -->
          <ul class="left">
            <li><%= link_to 'Book', bookings_path %></li>
            <li><%= link_to 'All Courses', courses_path %></li>
            <li><%= link_to 'Address', campuses_path %></li>
          </ul>
        </section>
      <% end %>
    </nav>
    
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>

    <%= yield %>

  </body>
</html>